/* SPDX-License-Identifier: ((GPL-2.0 WITH Linux-syscall-note) OR BSD-3-Clause) */
/* Do not edit directly, auto-generated from: */
/*	drbd_genl_ynl.yaml */
/* YNL-GEN uapi header */
/* To regenerate run: tools/net/ynl/ynl-regen.sh */

#ifndef _UAPI_LINUX_DRBD_GENL_H
#define _UAPI_LINUX_DRBD_GENL_H

#define DRBD_FAMILY_NAME	"drbd"
#define DRBD_FAMILY_VERSION	2

enum {
	DRBD_A_DRBD_CFG_REPLY_INFO_TEXT = 1,

	__DRBD_A_DRBD_CFG_REPLY_MAX,
	DRBD_A_DRBD_CFG_REPLY_MAX = (__DRBD_A_DRBD_CFG_REPLY_MAX - 1)
};

enum {
	DRBD_A_DRBD_CFG_CONTEXT_CTX_PEER_NODE_ID = 6,
	DRBD_A_DRBD_CFG_CONTEXT_CTX_VOLUME = 1,
	DRBD_A_DRBD_CFG_CONTEXT_CTX_RESOURCE_NAME,
	DRBD_A_DRBD_CFG_CONTEXT_CTX_MY_ADDR,
	DRBD_A_DRBD_CFG_CONTEXT_CTX_PEER_ADDR,
	DRBD_A_DRBD_CFG_CONTEXT_CTX_CONN_NAME,

	__DRBD_A_DRBD_CFG_CONTEXT_MAX,
	DRBD_A_DRBD_CFG_CONTEXT_MAX = (__DRBD_A_DRBD_CFG_CONTEXT_MAX - 1)
};

enum {
	DRBD_A_DISK_CONF_BACKING_DEV = 1,
	DRBD_A_DISK_CONF_META_DEV,
	DRBD_A_DISK_CONF_META_DEV_IDX,
	DRBD_A_DISK_CONF_DISK_SIZE,
	DRBD_A_DISK_CONF_ON_IO_ERROR = 6,
	DRBD_A_DISK_CONF_RESYNC_AFTER = 9,
	DRBD_A_DISK_CONF_AL_EXTENTS,
	DRBD_A_DISK_CONF_DISK_BARRIER = 16,
	DRBD_A_DISK_CONF_DISK_FLUSHES,
	DRBD_A_DISK_CONF_DISK_DRAIN,
	DRBD_A_DISK_CONF_MD_FLUSHES,
	DRBD_A_DISK_CONF_DISK_TIMEOUT,
	DRBD_A_DISK_CONF_READ_BALANCING,
	DRBD_A_DISK_CONF_UNPLUG_WATERMARK,
	DRBD_A_DISK_CONF_RS_DISCARD_GRANULARITY = 25,
	DRBD_A_DISK_CONF_AL_UPDATES = 23,
	DRBD_A_DISK_CONF_DISCARD_ZEROES_IF_ALIGNED,
	DRBD_A_DISK_CONF_DISABLE_WRITE_SAME = 26,
	DRBD_A_DISK_CONF_D_BITMAP,

	__DRBD_A_DISK_CONF_MAX,
	DRBD_A_DISK_CONF_MAX = (__DRBD_A_DISK_CONF_MAX - 1)
};

enum {
	DRBD_A_RES_OPTS_CPU_MASK = 1,
	DRBD_A_RES_OPTS_ON_NO_DATA,
	DRBD_A_RES_OPTS_AUTO_PROMOTE,
	DRBD_A_RES_OPTS_NODE_ID,
	DRBD_A_RES_OPTS_PEER_ACK_WINDOW,
	DRBD_A_RES_OPTS_TWOPC_TIMEOUT,
	DRBD_A_RES_OPTS_TWOPC_RETRY_TIMEOUT,
	DRBD_A_RES_OPTS_PEER_ACK_DELAY,
	DRBD_A_RES_OPTS_AUTO_PROMOTE_TIMEOUT,
	DRBD_A_RES_OPTS_NR_REQUESTS,
	DRBD_A_RES_OPTS_QUORUM,
	DRBD_A_RES_OPTS_ON_NO_QUORUM,
	DRBD_A_RES_OPTS_QUORUM_MIN_REDUNDANCY,
	DRBD_A_RES_OPTS_ON_SUSP_PRIMARY_OUTDATED,
	DRBD_A_RES_OPTS_DRBD8_COMPAT_MODE,
	DRBD_A_RES_OPTS_EXPLICIT_DRBD8_COMPAT,

	__DRBD_A_RES_OPTS_MAX,
	DRBD_A_RES_OPTS_MAX = (__DRBD_A_RES_OPTS_MAX - 1)
};

enum {
	DRBD_A_NET_CONF_SHARED_SECRET = 1,
	DRBD_A_NET_CONF_CRAM_HMAC_ALG,
	DRBD_A_NET_CONF_INTEGRITY_ALG,
	DRBD_A_NET_CONF_VERIFY_ALG,
	DRBD_A_NET_CONF_CSUMS_ALG,
	DRBD_A_NET_CONF_WIRE_PROTOCOL,
	DRBD_A_NET_CONF_CONNECT_INT,
	DRBD_A_NET_CONF_TIMEOUT,
	DRBD_A_NET_CONF_PING_INT,
	DRBD_A_NET_CONF_PING_TIMEO,
	DRBD_A_NET_CONF_SNDBUF_SIZE,
	DRBD_A_NET_CONF_RCVBUF_SIZE,
	DRBD_A_NET_CONF_KO_COUNT,
	DRBD_A_NET_CONF_MAX_EPOCH_SIZE = 15,
	DRBD_A_NET_CONF_AFTER_SB_0P = 17,
	DRBD_A_NET_CONF_AFTER_SB_1P,
	DRBD_A_NET_CONF_AFTER_SB_2P,
	DRBD_A_NET_CONF_RR_CONFLICT,
	DRBD_A_NET_CONF_ON_CONGESTION,
	DRBD_A_NET_CONF_CONG_FILL,
	DRBD_A_NET_CONF_CONG_EXTENTS,
	DRBD_A_NET_CONF_TWO_PRIMARIES,
	DRBD_A_NET_CONF_TCP_CORK = 26,
	DRBD_A_NET_CONF_ALWAYS_ASBP,
	DRBD_A_NET_CONF_USE_RLE = 29,
	DRBD_A_NET_CONF_FENCING_POLICY,
	DRBD_A_NET_CONF_NAME,
	DRBD_A_NET_CONF_CSUMS_AFTER_CRASH_ONLY = 33,
	DRBD_A_NET_CONF_SOCK_CHECK_TIMEO,
	DRBD_A_NET_CONF_TRANSPORT_NAME,
	DRBD_A_NET_CONF_MAX_BUFFERS,
	DRBD_A_NET_CONF_ALLOW_REMOTE_READ,
	DRBD_A_NET_CONF_TLS,
	DRBD_A_NET_CONF_TLS_PRIVKEY,
	DRBD_A_NET_CONF_TLS_CERTIFICATE,
	DRBD_A_NET_CONF_TLS_KEYRING,
	DRBD_A_NET_CONF_LOAD_BALANCE_PATHS,
	DRBD_A_NET_CONF_RDMA_CTRL_RCVBUF_SIZE,
	DRBD_A_NET_CONF_RDMA_CTRL_SNDBUF_SIZE,

	__DRBD_A_NET_CONF_MAX,
	DRBD_A_NET_CONF_MAX = (__DRBD_A_NET_CONF_MAX - 1)
};

enum {
	DRBD_A_SET_ROLE_PARMS_FORCE = 1,

	__DRBD_A_SET_ROLE_PARMS_MAX,
	DRBD_A_SET_ROLE_PARMS_MAX = (__DRBD_A_SET_ROLE_PARMS_MAX - 1)
};

enum {
	DRBD_A_RESIZE_PARMS_RESIZE_SIZE = 1,
	DRBD_A_RESIZE_PARMS_RESIZE_FORCE,
	DRBD_A_RESIZE_PARMS_NO_RESYNC,
	DRBD_A_RESIZE_PARMS_AL_STRIPES,
	DRBD_A_RESIZE_PARMS_AL_STRIPE_SIZE,

	__DRBD_A_RESIZE_PARMS_MAX,
	DRBD_A_RESIZE_PARMS_MAX = (__DRBD_A_RESIZE_PARMS_MAX - 1)
};

enum {
	DRBD_A_START_OV_PARMS_OV_START_SECTOR = 1,
	DRBD_A_START_OV_PARMS_OV_STOP_SECTOR,

	__DRBD_A_START_OV_PARMS_MAX,
	DRBD_A_START_OV_PARMS_MAX = (__DRBD_A_START_OV_PARMS_MAX - 1)
};

enum {
	DRBD_A_NEW_C_UUID_PARMS_CLEAR_BM = 1,
	DRBD_A_NEW_C_UUID_PARMS_FORCE_RESYNC,

	__DRBD_A_NEW_C_UUID_PARMS_MAX,
	DRBD_A_NEW_C_UUID_PARMS_MAX = (__DRBD_A_NEW_C_UUID_PARMS_MAX - 1)
};

enum {
	DRBD_A_TIMEOUT_PARMS_TIMEOUT_TYPE = 1,

	__DRBD_A_TIMEOUT_PARMS_MAX,
	DRBD_A_TIMEOUT_PARMS_MAX = (__DRBD_A_TIMEOUT_PARMS_MAX - 1)
};

enum {
	DRBD_A_DISCONNECT_PARMS_FORCE_DISCONNECT = 1,

	__DRBD_A_DISCONNECT_PARMS_MAX,
	DRBD_A_DISCONNECT_PARMS_MAX = (__DRBD_A_DISCONNECT_PARMS_MAX - 1)
};

enum {
	DRBD_A_DETACH_PARMS_FORCE_DETACH = 1,
	DRBD_A_DETACH_PARMS_INTENTIONAL_DISKLESS_DETACH,

	__DRBD_A_DETACH_PARMS_MAX,
	DRBD_A_DETACH_PARMS_MAX = (__DRBD_A_DETACH_PARMS_MAX - 1)
};

enum {
	DRBD_A_DEVICE_CONF_MAX_BIO_SIZE = 1,
	DRBD_A_DEVICE_CONF_INTENTIONAL_DISKLESS,
	DRBD_A_DEVICE_CONF_BLOCK_SIZE,
	DRBD_A_DEVICE_CONF_DISCARD_GRANULARITY,

	__DRBD_A_DEVICE_CONF_MAX,
	DRBD_A_DEVICE_CONF_MAX = (__DRBD_A_DEVICE_CONF_MAX - 1)
};

enum {
	DRBD_A_RESOURCE_INFO_RES_ROLE = 1,
	DRBD_A_RESOURCE_INFO_RES_SUSP,
	DRBD_A_RESOURCE_INFO_RES_SUSP_NOD,
	DRBD_A_RESOURCE_INFO_RES_SUSP_FEN,
	DRBD_A_RESOURCE_INFO_RES_SUSP_QUORUM,
	DRBD_A_RESOURCE_INFO_RES_FAIL_IO,

	__DRBD_A_RESOURCE_INFO_MAX,
	DRBD_A_RESOURCE_INFO_MAX = (__DRBD_A_RESOURCE_INFO_MAX - 1)
};

enum {
	DRBD_A_DEVICE_INFO_DEV_DISK_STATE = 1,
	DRBD_A_DEVICE_INFO_IS_INTENTIONAL_DISKLESS,
	DRBD_A_DEVICE_INFO_DEV_HAS_QUORUM,
	DRBD_A_DEVICE_INFO_DEV_IS_OPEN = 5,
	DRBD_A_DEVICE_INFO_BACKING_DEV_PATH = 4,

	__DRBD_A_DEVICE_INFO_MAX,
	DRBD_A_DEVICE_INFO_MAX = (__DRBD_A_DEVICE_INFO_MAX - 1)
};

enum {
	DRBD_A_CONNECTION_INFO_CONN_CONNECTION_STATE = 1,
	DRBD_A_CONNECTION_INFO_CONN_ROLE,

	__DRBD_A_CONNECTION_INFO_MAX,
	DRBD_A_CONNECTION_INFO_MAX = (__DRBD_A_CONNECTION_INFO_MAX - 1)
};

enum {
	DRBD_A_PEER_DEVICE_INFO_PEER_REPL_STATE = 1,
	DRBD_A_PEER_DEVICE_INFO_PEER_DISK_STATE,
	DRBD_A_PEER_DEVICE_INFO_PEER_RESYNC_SUSP_USER,
	DRBD_A_PEER_DEVICE_INFO_PEER_RESYNC_SUSP_PEER,
	DRBD_A_PEER_DEVICE_INFO_PEER_RESYNC_SUSP_DEPENDENCY,
	DRBD_A_PEER_DEVICE_INFO_PEER_IS_INTENTIONAL_DISKLESS,
	DRBD_A_PEER_DEVICE_INFO_PEER_RESYNC_SUSP_MAX_PARALLEL,

	__DRBD_A_PEER_DEVICE_INFO_MAX,
	DRBD_A_PEER_DEVICE_INFO_MAX = (__DRBD_A_PEER_DEVICE_INFO_MAX - 1)
};

enum {
	DRBD_A_RESOURCE_STATISTICS_RES_STAT_WRITE_ORDERING = 1,

	__DRBD_A_RESOURCE_STATISTICS_MAX,
	DRBD_A_RESOURCE_STATISTICS_MAX = (__DRBD_A_RESOURCE_STATISTICS_MAX - 1)
};

enum {
	DRBD_A_DEVICE_STATISTICS_DEV_SIZE = 1,
	DRBD_A_DEVICE_STATISTICS_DEV_READ,
	DRBD_A_DEVICE_STATISTICS_DEV_WRITE,
	DRBD_A_DEVICE_STATISTICS_DEV_AL_WRITES,
	DRBD_A_DEVICE_STATISTICS_DEV_BM_WRITES,
	DRBD_A_DEVICE_STATISTICS_DEV_UPPER_PENDING,
	DRBD_A_DEVICE_STATISTICS_DEV_LOWER_PENDING,
	DRBD_A_DEVICE_STATISTICS_DEV_UPPER_BLOCKED,
	DRBD_A_DEVICE_STATISTICS_DEV_LOWER_BLOCKED,
	DRBD_A_DEVICE_STATISTICS_DEV_AL_SUSPENDED,
	DRBD_A_DEVICE_STATISTICS_DEV_EXPOSED_DATA_UUID,
	DRBD_A_DEVICE_STATISTICS_DEV_CURRENT_UUID,
	DRBD_A_DEVICE_STATISTICS_DEV_DISK_FLAGS,
	DRBD_A_DEVICE_STATISTICS_HISTORY_UUIDS,

	__DRBD_A_DEVICE_STATISTICS_MAX,
	DRBD_A_DEVICE_STATISTICS_MAX = (__DRBD_A_DEVICE_STATISTICS_MAX - 1)
};

enum {
	DRBD_A_CONNECTION_STATISTICS_CONN_CONGESTED = 1,
	DRBD_A_CONNECTION_STATISTICS_AP_IN_FLIGHT,
	DRBD_A_CONNECTION_STATISTICS_RS_IN_FLIGHT,

	__DRBD_A_CONNECTION_STATISTICS_MAX,
	DRBD_A_CONNECTION_STATISTICS_MAX = (__DRBD_A_CONNECTION_STATISTICS_MAX - 1)
};

enum {
	DRBD_A_PEER_DEVICE_STATISTICS_PEER_DEV_RECEIVED = 1,
	DRBD_A_PEER_DEVICE_STATISTICS_PEER_DEV_SENT,
	DRBD_A_PEER_DEVICE_STATISTICS_PEER_DEV_PENDING,
	DRBD_A_PEER_DEVICE_STATISTICS_PEER_DEV_UNACKED,
	DRBD_A_PEER_DEVICE_STATISTICS_PEER_DEV_OUT_OF_SYNC,
	DRBD_A_PEER_DEVICE_STATISTICS_PEER_DEV_RESYNC_FAILED,
	DRBD_A_PEER_DEVICE_STATISTICS_PEER_DEV_BITMAP_UUID,
	DRBD_A_PEER_DEVICE_STATISTICS_PEER_DEV_FLAGS = 9,
	DRBD_A_PEER_DEVICE_STATISTICS_PEER_DEV_RS_TOTAL,
	DRBD_A_PEER_DEVICE_STATISTICS_PEER_DEV_OV_START_SECTOR,
	DRBD_A_PEER_DEVICE_STATISTICS_PEER_DEV_OV_STOP_SECTOR,
	DRBD_A_PEER_DEVICE_STATISTICS_PEER_DEV_OV_POSITION,
	DRBD_A_PEER_DEVICE_STATISTICS_PEER_DEV_OV_LEFT,
	DRBD_A_PEER_DEVICE_STATISTICS_PEER_DEV_OV_SKIPPED,
	DRBD_A_PEER_DEVICE_STATISTICS_PEER_DEV_RS_SAME_CSUM,
	DRBD_A_PEER_DEVICE_STATISTICS_PEER_DEV_RS_DT_START_MS,
	DRBD_A_PEER_DEVICE_STATISTICS_PEER_DEV_RS_PAUSED_MS,
	DRBD_A_PEER_DEVICE_STATISTICS_PEER_DEV_RS_DT0_MS,
	DRBD_A_PEER_DEVICE_STATISTICS_PEER_DEV_RS_DB0_SECTORS,
	DRBD_A_PEER_DEVICE_STATISTICS_PEER_DEV_RS_DT1_MS,
	DRBD_A_PEER_DEVICE_STATISTICS_PEER_DEV_RS_DB1_SECTORS,
	DRBD_A_PEER_DEVICE_STATISTICS_PEER_DEV_RS_C_SYNC_RATE,
	DRBD_A_PEER_DEVICE_STATISTICS_PEER_DEV_UUID_FLAGS,

	__DRBD_A_PEER_DEVICE_STATISTICS_MAX,
	DRBD_A_PEER_DEVICE_STATISTICS_MAX = (__DRBD_A_PEER_DEVICE_STATISTICS_MAX - 1)
};

enum {
	DRBD_A_DRBD_NOTIFICATION_HEADER_NH_TYPE = 1,

	__DRBD_A_DRBD_NOTIFICATION_HEADER_MAX,
	DRBD_A_DRBD_NOTIFICATION_HEADER_MAX = (__DRBD_A_DRBD_NOTIFICATION_HEADER_MAX - 1)
};

enum {
	DRBD_A_DRBD_HELPER_INFO_HELPER_NAME = 1,
	DRBD_A_DRBD_HELPER_INFO_HELPER_STATUS,

	__DRBD_A_DRBD_HELPER_INFO_MAX,
	DRBD_A_DRBD_HELPER_INFO_MAX = (__DRBD_A_DRBD_HELPER_INFO_MAX - 1)
};

enum {
	DRBD_A_INVALIDATE_PARMS_SYNC_FROM_PEER_NODE_ID = 1,
	DRBD_A_INVALIDATE_PARMS_RESET_BITMAP,

	__DRBD_A_INVALIDATE_PARMS_MAX,
	DRBD_A_INVALIDATE_PARMS_MAX = (__DRBD_A_INVALIDATE_PARMS_MAX - 1)
};

enum {
	DRBD_A_FORGET_PEER_PARMS_FORGET_PEER_NODE_ID = 1,

	__DRBD_A_FORGET_PEER_PARMS_MAX,
	DRBD_A_FORGET_PEER_PARMS_MAX = (__DRBD_A_FORGET_PEER_PARMS_MAX - 1)
};

enum {
	DRBD_A_PEER_DEVICE_CONF_RESYNC_RATE = 1,
	DRBD_A_PEER_DEVICE_CONF_C_PLAN_AHEAD,
	DRBD_A_PEER_DEVICE_CONF_C_DELAY_TARGET,
	DRBD_A_PEER_DEVICE_CONF_C_FILL_TARGET,
	DRBD_A_PEER_DEVICE_CONF_C_MAX_RATE,
	DRBD_A_PEER_DEVICE_CONF_C_MIN_RATE,
	DRBD_A_PEER_DEVICE_CONF_BITMAP,
	DRBD_A_PEER_DEVICE_CONF_RESYNC_WITHOUT_REPLICATION,
	DRBD_A_PEER_DEVICE_CONF_PEER_TIEBREAKER,

	__DRBD_A_PEER_DEVICE_CONF_MAX,
	DRBD_A_PEER_DEVICE_CONF_MAX = (__DRBD_A_PEER_DEVICE_CONF_MAX - 1)
};

enum {
	DRBD_A_PATH_PARMS_MY_ADDR = 1,
	DRBD_A_PATH_PARMS_PEER_ADDR,

	__DRBD_A_PATH_PARMS_MAX,
	DRBD_A_PATH_PARMS_MAX = (__DRBD_A_PATH_PARMS_MAX - 1)
};

enum {
	DRBD_A_CONNECT_PARMS_TENTATIVE = 1,
	DRBD_A_CONNECT_PARMS_DISCARD_MY_DATA,

	__DRBD_A_CONNECT_PARMS_MAX,
	DRBD_A_CONNECT_PARMS_MAX = (__DRBD_A_CONNECT_PARMS_MAX - 1)
};

enum {
	DRBD_A_DRBD_PATH_INFO_PATH_ESTABLISHED = 1,

	__DRBD_A_DRBD_PATH_INFO_MAX,
	DRBD_A_DRBD_PATH_INFO_MAX = (__DRBD_A_DRBD_PATH_INFO_MAX - 1)
};

enum {
	DRBD_A_RENAME_RESOURCE_PARMS_NEW_RESOURCE_NAME = 1,

	__DRBD_A_RENAME_RESOURCE_PARMS_MAX,
	DRBD_A_RENAME_RESOURCE_PARMS_MAX = (__DRBD_A_RENAME_RESOURCE_PARMS_MAX - 1)
};

enum {
	DRBD_A_RENAME_RESOURCE_INFO_RES_NEW_NAME = 1,

	__DRBD_A_RENAME_RESOURCE_INFO_MAX,
	DRBD_A_RENAME_RESOURCE_INFO_MAX = (__DRBD_A_RENAME_RESOURCE_INFO_MAX - 1)
};

enum {
	DRBD_A_INVALIDATE_PEER_PARMS_P_RESET_BITMAP = 1,

	__DRBD_A_INVALIDATE_PEER_PARMS_MAX,
	DRBD_A_INVALIDATE_PEER_PARMS_MAX = (__DRBD_A_INVALIDATE_PEER_PARMS_MAX - 1)
};

enum {
	DRBD_A_SUSPEND_IO_PARMS_BDEV_FREEZE = 1,

	__DRBD_A_SUSPEND_IO_PARMS_MAX,
	DRBD_A_SUSPEND_IO_PARMS_MAX = (__DRBD_A_SUSPEND_IO_PARMS_MAX - 1)
};

enum {
	DRBD_NLA_CFG_REPLY = 1,
	DRBD_NLA_CFG_CONTEXT,
	DRBD_NLA_DISK_CONF,
	DRBD_NLA_RESOURCE_OPTS,
	DRBD_NLA_NET_CONF,
	DRBD_NLA_SET_ROLE_PARMS,
	DRBD_NLA_RESIZE_PARMS,
	DRBD_NLA_START_OV_PARMS = 9,
	DRBD_NLA_NEW_C_UUID_PARMS,
	DRBD_NLA_TIMEOUT_PARMS,
	DRBD_NLA_DISCONNECT_PARMS,
	DRBD_NLA_DETACH_PARMS,
	DRBD_NLA_DEVICE_CONF,
	DRBD_NLA_RESOURCE_INFO,
	DRBD_NLA_DEVICE_INFO,
	DRBD_NLA_CONNECTION_INFO,
	DRBD_NLA_PEER_DEVICE_INFO,
	DRBD_NLA_RESOURCE_STATISTICS,
	DRBD_NLA_DEVICE_STATISTICS,
	DRBD_NLA_CONNECTION_STATISTICS,
	DRBD_NLA_PEER_DEVICE_STATISTICS,
	DRBD_NLA_NOTIFICATION_HEADER,
	DRBD_NLA_HELPER,
	DRBD_NLA_INVALIDATE_PARMS,
	DRBD_NLA_FORGET_PEER_PARMS,
	DRBD_NLA_PEER_DEVICE_OPTS,
	DRBD_NLA_PATH_PARMS,
	DRBD_NLA_CONNECT_PARMS,
	DRBD_NLA_PATH_INFO,
	DRBD_NLA_RENAME_RESOURCE_PARMS,
	DRBD_NLA_RENAME_RESOURCE_INFO,
	DRBD_NLA_INVAL_PEER_PARAMS,
	DRBD_NLA_SUSPEND_IO_PARAMS,

	__DRBD_NLA_MAX,
	DRBD_NLA_MAX = (__DRBD_NLA_MAX - 1)
};

enum {
	DRBD_ADM_NEW_MINOR = 5,
	DRBD_ADM_DEL_MINOR,
	DRBD_ADM_NEW_RESOURCE,
	DRBD_ADM_DEL_RESOURCE,
	DRBD_ADM_RESOURCE_OPTS,
	DRBD_ADM_CONNECT,
	DRBD_ADM_DISCONNECT,
	DRBD_ADM_ATTACH,
	DRBD_ADM_RESIZE,
	DRBD_ADM_PRIMARY,
	DRBD_ADM_SECONDARY,
	DRBD_ADM_NEW_C_UUID,
	DRBD_ADM_START_OV,
	DRBD_ADM_DETACH,
	DRBD_ADM_INVALIDATE,
	DRBD_ADM_INVALIDATE_PEER,
	DRBD_ADM_PAUSE_SYNC,
	DRBD_ADM_RESUME_SYNC,
	DRBD_ADM_SUSPEND_IO,
	DRBD_ADM_RESUME_IO,
	DRBD_ADM_OUTDATE,
	DRBD_ADM_GET_TIMEOUT_TYPE,
	DRBD_ADM_DOWN,
	DRBD_ADM_DISK_OPTS,
	DRBD_ADM_NET_OPTS,
	DRBD_ADM_GET_RESOURCES,
	DRBD_ADM_GET_DEVICES,
	DRBD_ADM_GET_CONNECTIONS,
	DRBD_ADM_GET_PEER_DEVICES,
	DRBD_ADM_GET_INITIAL_STATE = 38,
	DRBD_ADM_FORGET_PEER = 42,
	DRBD_ADM_PEER_DEVICE_OPTS,
	DRBD_ADM_NEW_PEER,
	DRBD_ADM_NEW_PATH,
	DRBD_ADM_DEL_PEER,
	DRBD_ADM_DEL_PATH,
	DRBD_ADM_RENAME_RESOURCE = 49,
	DRBD_ADM_GET_PATHS,

	__DRBD_ADM_MAX,
	DRBD_ADM_MAX = (__DRBD_ADM_MAX - 1)
};

enum {
	DRBD_RESOURCE_STATE = 34,
	DRBD_DEVICE_STATE = 35,
	DRBD_CONNECTION_STATE = 36,
	DRBD_PEER_DEVICE_STATE = 37,
	DRBD_HELPER = 40,
	DRBD_INITIAL_STATE_DONE = 41,
	DRBD_PATH_STATE = 48,
};

#define DRBD_MCGRP_EVENTS	"events"

#endif /* _UAPI_LINUX_DRBD_GENL_H */
